import { useEffect, useRef } from "react";
import CardSkeleton from "@/components/shared/CardSkeleton";
import MasonaryGridLayout from "@/components/shared/MasonaryGridLayout";
import WebLayoutWrapper from "@/components/shared/WebLayoutWrapper";
import { useGetAllGenerations } from "@/lib/tanstack-query/queriesAndMutation";
import { Loader2 } from "lucide-react";

const ShowCase = () => {
  const {
    data: userGenerations,
    isLoading: isImageLoading,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
  } = useGetAllGenerations();

  const allDocuments =
    userGenerations?.pages.flatMap((page) => page.documents) ?? [];

  const observerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!hasNextPage || isFetchingNextPage) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          fetchNextPage();
        }
      },
      {
        root: null,
        rootMargin: "100px", 
        threshold: 0.1, 
      }
    );

    const currentObserverRef = observerRef.current;
    if (currentObserverRef) {
      observer.observe(currentObserverRef);
    }

    return () => {
      if (currentObserverRef) {
        observer.unobserve(currentObserverRef);
      }
    };
  }, [fetchNextPage, hasNextPage, isFetchingNextPage]);

  return (
    <WebLayoutWrapper>
      <div className="container py-4">
        {/* <div className="w-[95%] md:w-[99%] mx-auto"> 
          <Categories />
        </div> */}
        <div className="w-full flex flex-col gap-2 my-3">
          <h2 className="text-primary-black text-2xl md:text-4xl font-semibold">
            Explore the Retena.AI Gallery
          </h2>
          <p className="text-primary-blue3 text-sm md:text-base pl-2">
            Discover creative images generated by our community and find your
            next inspiration.
          </p>
        </div>
        <MasonaryGridLayout data={allDocuments} />
        {isImageLoading && <CardSkeleton card_number={10} />}
        {isFetchingNextPage && (
         <div className="w-full my-1 flex justify-center items-center">
           <Loader2 className="h-8 w-8 text-primary-black"/>
         </div>
        )}
        <div ref={observerRef} style={{ height: "1px" }} />
      </div>
    </WebLayoutWrapper>
  );
};

export default ShowCase;
