import CardSkeleton from "@/components/shared/CardSkeleton";
// import Categories from "@/components/shared/Categories";
import MasonaryGridLayout from "@/components/shared/MasonaryGridLayout";
import WebLayoutWrapper from "@/components/shared/WebLayoutWrapper";
import { useGetAllGenerations } from "@/lib/tanstack-query/queriesAndMutation";

const ShowCase = () => {
  const { data: userGenerations, isPending: isImageLoading } =
    useGetAllGenerations();

  console.log(userGenerations);

  return (
    <WebLayoutWrapper>
      <div className="container py-4">
        {/* <div className="w-[95%] md:w-[99%] mx-auto">
          <Categories />
        </div> */}
        <div className="w-full flex flex-col gap-2 my-3">
          <h2 className="text-primary-black text-2xl md:text-4xl font-semibold">
            Explore the Retina.AI Gallery
          </h2>
          <p className="text-primary-blue3 text-sm md:text-base pl-2">
            Discover creative images generated by our community and find your
            next inspiration.
          </p>
        </div>
        <MasonaryGridLayout data={userGenerations?.documents ?? []} />
        {isImageLoading && <CardSkeleton card_number={10} />}
      </div>
    </WebLayoutWrapper>
  );
};

export default ShowCase;
